#mongodb连接地址，集群用“;”隔开
spring:
  data:
    mongodb:
      #      host: 192.168.101.19
      #      host: 192.168.101.19
      host: localhost
      port: 27017
      database: SparkDBLPTest
    #      auto-index-creation: true
    rest:
      default-page-size: 30
  jpa:
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    # 连接超时时间
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
logging:
  level:
    org.springframework.data.mongodb.core: debug