#mongodb连接地址，集群用“;”隔开
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: SparkDBLPTest
    #      auto-index-creation: true

    rest:
      default-page-size: 30
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.data.mongodb.core: debug
